-- DROP TABLE IF EXISTS products;
-- DROP TABLE IF EXISTS styles;
-- DROP TABLE IF EXISTS features;
-- DROP TABLE IF EXISTS photos;
-- DROP TABLE IF EXISTS skus;
-- DROP TABLE IF EXISTS related;

CREATE TABLE IF NOT EXISTS products (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR NOT NULL,
  slogan VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  category VARCHAR NOT NULL,
  default_price VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
);

COPY products(id, name, slogan, description, category, default_price)
FROM '/Users/andy/Desktop/HackReactor/SDC/product.csv'
DELIMITER ','
CSV HEADER;

CREATE TABLE IF NOT EXISTS styles (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  productId INT REFERENCES products(id),
  style_name VARCHAR NOT NULL,
  sale_price VARCHAR(50),
  original_price VARCHAR(50),
  default_style BOOLEAN NOT NULL,
  PRIMARY KEY(id)
);

CREATE INDEX productId_key ON styles(productId);

COPY styles
FROM '/Users/andy/Desktop/HackReactor/SDC/styles.csv'
DELIMITER ','
CSV HEADER;

CREATE TABLE IF NOT EXISTS features (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  product_id INT REFERENCES products(id),
  feature VARCHAR,
  value VARCHAR
);

COPY features
FROM '/Users/andy/Desktop/HackReactor/SDC/features.csv'
DELIMITER ','
CSV HEADER;

CREATE TABLE IF NOT EXISTS related (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  current_product_id INT REFERENCES products(id),
  related_product_id INT REFERENCES products(id)
);

CREATE INDEX current_idx ON related(current_product_id);

COPY related(id, current_product_id, related_product_id)
FROM '/Users/andy/Desktop/HackReactor/SDC/related.csv'
DELIMITER ','
CSV HEADER;

CREATE TABLE IF NOT EXISTS skus (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  styleId INT REFERENCES styles(id),
  size VARCHAR NOT NUll,
  quantity INT DEFAULT 0,
  PRIMARY KEY(id)
);

CREATE INDEX styleId_idx ON skus(styleId);

COPY skus
FROM '/Users/andy/Desktop/HackReactor/SDC/skus.csv'
DELIMITER ','
CSV HEADER;

CREATE TABLE IF NOT EXISTS photos (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  styleId INT REFERENCES styles(id),
  url VARCHAR,
  thumbnail_url VARCHAR,
  PRIMARY KEY(id)
);

CREATE INDEX styleId ON photos(styleId);

COPY photos
FROM '/Users/andy/Desktop/HackReactor/SDC/photos.csv'
DELIMITER ','
CSV HEADER;